//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneUpgrade) DeepCopyInto(out *ControlPlaneUpgrade) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneUpgrade.
func (in *ControlPlaneUpgrade) DeepCopy() *ControlPlaneUpgrade {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneUpgrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlaneUpgrade) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneUpgradeList) DeepCopyInto(out *ControlPlaneUpgradeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControlPlaneUpgrade, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneUpgradeList.
func (in *ControlPlaneUpgradeList) DeepCopy() *ControlPlaneUpgradeList {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneUpgradeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlaneUpgradeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneUpgradeSpec) DeepCopyInto(out *ControlPlaneUpgradeSpec) {
	*out = *in
	out.Cluster = in.Cluster
	out.ControlPlane = in.ControlPlane
	if in.MachinesRequireUpgrade != nil {
		in, out := &in.MachinesRequireUpgrade, &out.MachinesRequireUpgrade
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	out.NewVersion = in.NewVersion
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneUpgradeSpec.
func (in *ControlPlaneUpgradeSpec) DeepCopy() *ControlPlaneUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneUpgradeStatus) DeepCopyInto(out *ControlPlaneUpgradeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneUpgradeStatus.
func (in *ControlPlaneUpgradeStatus) DeepCopy() *ControlPlaneUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesVersionBundle) DeepCopyInto(out *KubernetesVersionBundle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesVersionBundle.
func (in *KubernetesVersionBundle) DeepCopy() *KubernetesVersionBundle {
	if in == nil {
		return nil
	}
	out := new(KubernetesVersionBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeUpgrade) DeepCopyInto(out *NodeUpgrade) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeUpgrade.
func (in *NodeUpgrade) DeepCopy() *NodeUpgrade {
	if in == nil {
		return nil
	}
	out := new(NodeUpgrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeUpgrade) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeUpgradeList) DeepCopyInto(out *NodeUpgradeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeUpgrade, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeUpgradeList.
func (in *NodeUpgradeList) DeepCopy() *NodeUpgradeList {
	if in == nil {
		return nil
	}
	out := new(NodeUpgradeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeUpgradeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeUpgradeSpec) DeepCopyInto(out *NodeUpgradeSpec) {
	*out = *in
	out.Machine = in.Machine
	out.Node = in.Node
	out.NewVersion = in.NewVersion
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeUpgradeSpec.
func (in *NodeUpgradeSpec) DeepCopy() *NodeUpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(NodeUpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeUpgradeStatus) DeepCopyInto(out *NodeUpgradeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeUpgradeStatus.
func (in *NodeUpgradeStatus) DeepCopy() *NodeUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}
